services:
  api:
    build: .
    image: loc-recsys-app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - APP_MODE=api
      - PORT=8000
    restart: unless-stopped

  ui:
    build: .
    image: loc-recsys-app
    ports:
      - "8501:8501"
    env_file: .env
    environment:
      - APP_MODE=ui
      - PORT=8501
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped
