target-version = "py311"
line-length = 100

[lint]
select = [
    "E9",   # syntax error
    "F63",  # invalid comparison
    "F7",   # syntax-ish (break/return di luar tempatnya)
    "F82",  # undefined name
    "F401", # unused import
]
